// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"

	"github.com/tabbed/pqtype"
)

type Building struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Level     int32        `json:"level"`
	Rarity    string       `json:"rarity"`
	Owner     string       `json:"owner"`
	Isur      bool         `json:"isur"`
	TokenID   int32        `json:"token_id"`
	IsBurned  bool         `json:"is_burned"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type CEFile struct {
	ID          int32         `json:"id"`
	RarityID    sql.NullInt32 `json:"rarity_id"`
	CharacterID sql.NullInt32 `json:"character_id"`
	EquipmentID sql.NullInt32 `json:"equipment_id"`
	IpfsUri     string        `json:"ipfs_uri"`
	ImageUri    string        `json:"image_uri"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
}

type Card struct {
	ID             int32         `json:"id"`
	Name           string        `json:"name"`
	OwnerAddress   string        `json:"owner_address"`
	EquipmentID    sql.NullInt32 `json:"equipment_id"`
	CharacterID    sql.NullInt32 `json:"character_id"`
	Level          int32         `json:"level"`
	TokenID        int32         `json:"token_id"`
	RarityID       int32         `json:"rarity_id"`
	IsUr           bool          `json:"is_ur"`
	Locked         bool          `json:"locked"`
	NumberOfSkills int32         `json:"number_of_skills"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      sql.NullTime  `json:"updated_at"`
	DeletedAt      sql.NullTime  `json:"deleted_at"`
	CEFileID       sql.NullInt32 `json:"c_e_file_id"`
}

type Character struct {
	ID            int32                 `json:"id"`
	Name          string                `json:"name"`
	Description   pqtype.NullRawMessage `json:"description"`
	AttackRange   int32                 `json:"attack_range"`
	EquipmentSlot int32                 `json:"equipment_slot"`
	CountryID     int32                 `json:"country_id"`
	GenderID      int32                 `json:"gender_id"`
	AttributeID   int32                 `json:"attribute_id"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
	DeletedAt     sql.NullTime          `json:"deleted_at"`
}

type Equipment struct {
	ID           int32                 `json:"id"`
	Name         string                `json:"name"`
	CriticalRate int32                 `json:"critical_rate"`
	AttackRange  int32                 `json:"attack_range"`
	Description  pqtype.NullRawMessage `json:"description"`
	TypeID       int32                 `json:"type_id"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
	DeletedAt    sql.NullTime          `json:"deleted_at"`
}

type EquipmentType struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type MinigameRank struct {
	ID            int32        `json:"id"`
	WalletAddress string       `json:"wallet_address"`
	Mark          int32        `json:"mark"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

type Rarity struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID            int32          `json:"id"`
	WalletAddress sql.NullString `json:"wallet_address"`
	Email         string         `json:"email"`
	Name          sql.NullString `json:"name"`
	Rank          int32          `json:"rank"`
	Balance       int32          `json:"balance"`
	Stamina       int32          `json:"stamina"`
	OtpAuthSecret sql.NullString `json:"otp_auth_secret"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
}

type Whitelist struct {
	ID            int32        `json:"id"`
	WalletAddress string       `json:"wallet_address"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}
