// Code generated by sqlc. DO NOT EDIT.
// source: whitelist.sql

package sqlc

import (
	"context"
)

const getWhitelistByWallet = `-- name: GetWhitelistByWallet :one
SELECT id, wallet_address, created_at, updated_at, deleted_at FROM public.whitelist
WHERE wallet_address = $1 LIMIT 1
`

func (q *Queries) GetWhitelistByWallet(ctx context.Context, walletAddress string) (Whitelist, error) {
	row := q.db.QueryRowContext(ctx, getWhitelistByWallet, walletAddress)
	var i Whitelist
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
